"""empty message

Revision ID: 8ea2c2fe3f11
Revises: e4df30d765b4
Create Date: 2019-03-25 17:54:06.248893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea2c2fe3f11'
down_revision = 'e4df30d765b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teltransfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transferidcard', sa.BigInteger(), nullable=True),
    sa.Column('teloperation', sa.String(length=200), nullable=False),
    sa.Column('teltransfertime', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teltransfer')
    # ### end Alembic commands ###
