"""empty message

Revision ID: 912c7feb6eb7
Revises: 
Create Date: 2019-03-12 11:32:18.712856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912c7feb6eb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tellername', sa.String(length=80), nullable=True),
    sa.Column('tellcard', sa.BigInteger(), nullable=True),
    sa.Column('tellpwd', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tellcard')
    )
    op.create_index(op.f('ix_teller_tellername'), 'teller', ['tellername'], unique=False)
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transferidcard', sa.BigInteger(), nullable=True),
    sa.Column('operation', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('usersex', sa.String(length=8), nullable=True),
    sa.Column('idcard', sa.BigInteger(), nullable=True),
    sa.Column('userpwd', sa.String(length=80), nullable=True),
    sa.Column('userphone', sa.BigInteger(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idcard'),
    sa.UniqueConstraint('userphone')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bankcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bankname', sa.String(length=80), nullable=True),
    sa.Column('banktype', sa.String(length=80), nullable=True),
    sa.Column('banknum', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cardpwd', sa.Integer(), nullable=True),
    sa.Column('onActive', sa.Boolean(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankcard_banknum'), 'bankcard', ['banknum'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bankcard_banknum'), table_name='bankcard')
    op.drop_table('bankcard')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_teller_tellername'), table_name='teller')
    op.drop_table('teller')
    # ### end Alembic commands ###
