"""empty message

Revision ID: e4df30d765b4
Revises: 912c7feb6eb7
Create Date: 2019-03-13 20:05:36.337048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4df30d765b4'
down_revision = '912c7feb6eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('transfertime', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer', 'transfertime')
    # ### end Alembic commands ###
